mysite/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('all/', views.get_blogs, name='get_blogs')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

mysite/blog/models.py
from django.db import models

class Blog(models.Model):
    name = models.CharField(max_length = 128)
    tagline = models.TextField()

    def __str__(self):
        return self.name



class Author(models.Model):
    name = models.CharField(max_length = 64)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Entry(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    text = models.TextField()
    pub_date = models.DateField()
    mod_date = models.DateField()
    authors = models.ManyToManyField(Author)
    number_of_comments = models.IntegerField(default=0)

    def __str__(self):
        return self.title

mysite/polls/models.py
import datetime

from django.db import models
from django.test import Client
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    

    def was_published_recently(self):
        now = timezone.now()
        return  now - datetime.timedelta(days=2) <= self.pub_date <= now 


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    chice_text = models.CharField(max_length=80)
    votes = models.IntegerField(default=0)
      

mysite/polls/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

mysite/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *

from pprint import pprint


def index(request):
    return HttpResponse('Hello again django nube. I missed you!')


def get_blogs(request):
    pprint(data)
    blogs = Blog.objects.all()

    return HttpResponse([{'blogname': b.name} for b in blogs])

mysite/polls/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AnonymousUser
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic

from polls.forms import LoginForm

from polls.models import Choice, Question




# class IndexView(generic.ListView):
#     template_name = 'polls/index.html'
#     context_object_name = 'latest_question_list' 

#     def get_queryset(self):
#         return Question.objects.order_by('-pub_date')[:20]


# class DetailView(generic.DetailView):
#     template_name = 'polls/detail.html'
#     model = Question


# class ResultsView(generic.DetailView):
#     template_name = 'polls/result.html'
#     model = Question



def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list, 
        'is_logged': request.user.is_authenticated
        }
    
    return render(request, 'polls/index.html', context)


@login_required(login_url='polls:login')
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/result.html', {'question': question})


def vote(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except KeyError:
        return render(
            request, 
            'polls/detail.html', 
            {'question': question})
    else:
        selected_choice.votes =  F('votes') + 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request, 
                username=form.data['username'], 
                password=form.data['password']
                )
            if user is not None and user.is_active:
                login(request, user)
            return HttpResponseRedirect(reverse('polls:index', args=()))
    form = LoginForm()
    return render(request, 'polls/login.html', {'form':form})


def user_logout(request):
    logout(request)
    print('request. user', type(request.user))
    return HttpResponseRedirect(reverse('polls:index', args=()))    

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Polls App</title>
</head>
<body>
{}
</body>
</html>

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Polls</title>
</head>
<body>
   <h1>{{question.question_text}}</h1>
  <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}

       {% for choice in question.choice_set.all %}
           <input type="radio" name="choice" id="{{ forloop.counter }}" value="{{choice.id}}">
           <label for="choice{{ forloop.counter }}">{{choice.chice_text}}</label><br>
        {% endfor %}

    <input type="submit" name="Vote">
  </form>

  <p>This page was visited {{polls_count}} times</p>

</body>
</html>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Polls</title>
</head>
<body>
    <p>Gutten morgen</p>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}"> {{question.question_text}} </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls available.</p>
    {% endif %}
    {% if is_logged %}
        <a href="{% url 'polls:logout' %}"> logout</a>
    {% else %}
         <a href="{% url 'polls:login' %}"> login</a>
    {% endif %}
</body>
</html>

mysite/polls/templates/polls/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Polls</title>
</head>
<body>
  <form method="post", action="{% url 'polls:login'%}"/>
    {% csrf_token %}
    <table>
      <tr>
        <td> {{form.username.label_tag}}</td>
        <td> {{form.username}}</td>
      </tr>
      <tr>
        <td> {{form.password.label_tag}}</td>
        <td> {{form.password}}</td>
      </tr>
      <input type="submit" value="login"/>

    </table>


</body>
</html>

mysite/polls/templates/polls/result.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Polls</title>
</head>
<body>
   <h1>{{question.question_text}}</h1>
    
    <ul>
      {% for choice in question.choice_set.all %}
      <li>{{ choice.chice_text }}    {{choice.votes}} votes</li>
      {% endfor %}
    </ul>
      
 <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>